[supervisord]
nodaemon=true

[program:laravel_octane]
command=php -d variables_order=EGPCS artisan octane:start --server=swoole --host=0.0.0.0 --port=8080 --workers=8
redirect_stderr=true
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)s
stdout_logfile=/app/storage/logs/swoole_http.log
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
